spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8181/catalog-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalog-service
                fallbackuri: forward:/catalogServiceFallBack

        - id: inventory-service
          uri: http://localhost:8282/inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventory-service
                fallbackuri: forward:/inventoryServiceFallBack

        - id: product-service
          uri: http://localhost:8383/product-service
          predicates:
              - Path=/api/productClients/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productServiceFallBack


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
